In [2]:
import time
import numpy as np 

In [3]:
my_arr = np.arange(100000)
my_list = list(range(100000))

In [4]:
start_time = time.time()
for _ in range(10):
    my_arr2 = my_arr * 2

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0010001659393310547 seconds ---


In [5]:
start_time = time.time()
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.031014680862426758 seconds ---


In [7]:
start_time = time.time()
for _ in range(10):
    for i in range(100000):
        my_arr[i] = my_arr[i] << 1

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.18872356414794922 seconds ---


In [8]:
a = np.array([[2., 3., 5.],
                [7., 8., 9.]])

In [9]:
np.shape(a)

(2, 3)

In [11]:
                data1 = [1., 0.3, 2, 4, -2]
                arr1 = np.array(data1)

                data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
                arr2 = np.array(data2)
                print(arr1.ndim)
                print(arr2.ndim)

                print(arr1.shape)
                print(arr2.shape)

                print(arr1.size)
                print(arr2.size)

                print(arr1.dtype)    # float64 
                print(arr2.dtype)    # int32

1
2
(5,)
(2, 4)
5
8
float64
int32


In [12]:
x = np.zeros((2,3,4))
x.shape

(2, 3, 4)

In [22]:
x = np.zeros(3, dtype="string_")
x.dtype

dtype('S1')

In [37]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[1:, 1:])

[[4]
 [6]]


In [40]:
a = np.array([1, 1, 1])
1 / (2 * a)
b = np.array([[1, 2, 3], [4, 5, 6]])

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(a))       # 6
print(np.argmax(a))    # 5 
print(np.unravel_index(np.argmax(a), a.shape))  # (1, 2)
print(np.sum(a))       # 21
print(a.mean(axis=1))  # [2., 5.]
print(a.sum(axis=0))   # [5, 7, 9]
print(np.std(a))       # 1.7078...

6
5
(1, 2)
21
[2. 5.]
[5 7 9]
1.707825127659933


In [71]:
              arr = np.array([1, 2, 3, 4])

              vista = arr.reshape((2, 2))
              vista[0, 0] = -1 

              print(arr[0])    # -1

              arr[1:] = 10
              print(vista)      # [[-1 10]
                            
        
              copia = arr.astype(float)
              copia[0] = 5.0
              print(arr[0])   # -1
              copia
              

-1
[[-1 10]
 [10 10]]
-1


array([ 5., 10., 10., 10.])

In [ ]:
import pandas as pd

datos = [3, -2, 0, 42]                            
obj = pd.Series(datos)
print(obj)
# 0     3
# 1    -2
# 2     0
# 3    42
# dtype: int64

obj2 = pd.Series(datos, index=['a', 'd', 'g', 'w'])
print(obj2)

0     3
1    -2
2     0
3    42
dtype: int64
a     3
d    -2
g     0
w    42
dtype: int64
0     3
1    -2
2     0
3    42
dtype: int64


In [76]:

obj2 = pd.Series(datos, index=['a', 'd', 'g', 'w'])
print(obj2)
# a     3
# d    -2
# g     0
# w    42
# dtype: int64





print(obj2['a'])    # 3
obj2['w'] = 100 
print(obj2[['a', 'w']])  

a     3
d    -2
g     0
w    42
dtype: int64
3
a      3
w    100
dtype: int64


In [ ]:
# Creamos una serie a partir de un diccionario
datos_ciudades = {'A Coruña': 249261, 'Lugo': 99482, 
                  'Ourense': 104891, 'Pontevedra': 83077}
# Pero damos un índice distinto al del diccionario
ciudades = pd.Series(datos_ciudades, 
            index=['Santiago', 'Lugo', 'Ourense', 'Vigo'])
print(ciudades)    
# Santiago         NaN
# Lugo         99482.0
# Ourense     104891.0
# Vigo             NaN
# dtype: float64

pd.isnull(ciudades)     # También existe notnull()
# Santiago     True
# Lugo        False
# Ourense     False
# Vigo         True
# dtype: bool




nuevos_nacimientos = pd.Series({'Ourense': 5000, 'Vigo': 5000})
print(ciudades + nuevos_nacimientos)


SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (3610174660.py, line 3)