In [178]:
import time
import numpy as np 

In [179]:
my_arr = np.arange(100000)
my_list = list(range(100000))

In [180]:
start_time = time.time()
for _ in range(10):
    my_arr2 = my_arr * 2

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0015065670013427734 seconds ---


In [181]:
start_time = time.time()
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.029905319213867188 seconds ---


In [182]:
start_time = time.time()
for _ in range(10):
    for i in range(100000):
        my_arr[i] = my_arr[i] << 1

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.21507716178894043 seconds ---


In [183]:
a = np.array([[2., 3., 5.],
                [7., 8., 9.]])

In [184]:
np.shape(a)

(2, 3)

In [185]:
                data1 = [1., 0.3, 2, 4, -2]
                arr1 = np.array(data1)

                data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
                arr2 = np.array(data2)
                print(arr1.ndim)
                print(arr2.ndim)

                print(arr1.shape)
                print(arr2.shape)

                print(arr1.size)
                print(arr2.size)

                print(arr1.dtype)    # float64 
                print(arr2.dtype)    # int32

1
2
(5,)
(2, 4)
5
8
float64
int32


In [186]:
x = np.zeros((2,3,4))
x.shape

(2, 3, 4)

In [187]:
x = np.zeros(3, dtype="string_")
x.dtype

dtype('S1')

In [188]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[1:, 1:])

[[4]
 [6]]


In [189]:
a = np.array([1, 1, 1])
1 / (2 * a)
b = np.array([[1, 2, 3], [4, 5, 6]])

In [190]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(a))       # 6
print(np.argmax(a))    # 5 
print(np.unravel_index(np.argmax(a), a.shape))  # (1, 2)
print(np.sum(a))       # 21
print(a.mean(axis=1))  # [2., 5.]
print(a.sum(axis=0))   # [5, 7, 9]
print(np.std(a))       # 1.7078...

6
5
(1, 2)
21
[2. 5.]
[5 7 9]
1.707825127659933


In [191]:
              arr = np.array([1, 2, 3, 4])

              vista = arr.reshape((2, 2))
              vista[0, 0] = -1 

              print(arr[0])    # -1

              arr[1:] = 10
              print(vista)      # [[-1 10]
                            
        
              copia = arr.astype(float)
              copia[0] = 5.0
              print(arr[0])   # -1
              copia
              

-1
[[-1 10]
 [10 10]]
-1


array([ 5., 10., 10., 10.])

In [192]:
import pandas as pd

datos = [3, -2, 0, 42]                            
obj = pd.Series(datos)
print(obj)
# 0     3
# 1    -2
# 2     0
# 3    42
# dtype: int64

obj2 = pd.Series(datos, index=['a', 'd', 'g', 'w'])
print(obj2)

0     3
1    -2
2     0
3    42
dtype: int64
a     3
d    -2
g     0
w    42
dtype: int64


In [193]:

obj2 = pd.Series(datos, index=['a', 'd', 'g', 'w'])
print(obj2)
# a     3
# d    -2
# g     0
# w    42
# dtype: int64





print(obj2['a'])    # 3
obj2['w'] = 100 
print(obj2[['a', 'w']])  

a     3
d    -2
g     0
w    42
dtype: int64
3
a      3
w    100
dtype: int64


In [194]:
# Creamos una serie a partir de un diccionario
datos_ciudades = {'A Coruña': 249261, 'Lugo': 99482, 
                  'Ourense': 104891, 'Pontevedra': 83077}
# Pero damos un índice distinto al del diccionario
ciudades = pd.Series(datos_ciudades, 
            index=['Santiago', 'Lugo', 'Ourense', 'Vigo'])
print(ciudades)    
# Santiago         NaN
# Lugo         99482.0
# Ourense     104891.0
# Vigo             NaN
# dtype: float64

pd.isnull(ciudades)     # También existe notnull()
# Santiago     True
# Lugo        False
# Ourense     False
# Vigo         True
# dtype: bool




nuevos_nacimientos = pd.Series({'Ourense': 5000, 'Vigo': 5000})
print(ciudades + nuevos_nacimientos)


Santiago         NaN
Lugo         99482.0
Ourense     104891.0
Vigo             NaN
dtype: float64
Lugo             NaN
Ourense     109891.0
Santiago         NaN
Vigo             NaN
dtype: float64


In [195]:
datos = {'nombre': ["Marcos", "Eva", "Sara", "Xoel"],
            'edad': [40, 35, 23, 23],
            'tiene_perro': [False, True, True, False]
        }
# Con el parámetro columns podemos reordenar las columnas
# Si no se encuentran los datos para alguna columna, sus valores son NaNs
df = pd.DataFrame(datos, columns=['nombre', 'tiene_perro', 'sueldo', 'edad'])
print(df)

   nombre  tiene_perro sueldo  edad
0  Marcos        False    NaN    40
1     Eva         True    NaN    35
2    Sara         True    NaN    23
3    Xoel        False    NaN    23


In [196]:
datos2 = [
{'nombre': "Marcos", 'edad': 40, 'tiene_perro': False},
{'nombre': "Eva", 'edad': 35, 'tiene_perro': True},
{'nombre': "Xoel", 'edad': 23, 'tiene_perro': True}
]
df2 = pd.DataFrame(datos2)
print(df2)

   nombre  edad  tiene_perro
0  Marcos    40        False
1     Eva    35         True
2    Xoel    23         True


In [197]:
df2.nombre

0    Marcos
1       Eva
2      Xoel
Name: nombre, dtype: object

In [198]:
print(df2[:2])
#    nombre  edad  tiene_perro
# 0  Marcos    40        False
# 1     Eva    35         True

# "and" y "or" no funcionan, como en NumPy
filtrado = df2[(df2['edad'] < 30) | (df2['nombre'] == "Marcos")]  
print(filtrado)  

   nombre  edad  tiene_perro
0  Marcos    40        False
1     Eva    35         True
   nombre  edad  tiene_perro
0  Marcos    40        False
2    Xoel    23         True


In [199]:
df2

nombre  edad  tiene_perro
0  Marcos    40        False
1     Eva    35         True
2    Xoel    23         True

In [ ]:
datos = pd.DataFrame([[1., 6.5, 2.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
datos_limpios = datos.dropna()

print(datos)

print(datos_limpios)

NameError: name 'nan' is not defined